#! /bin/bash

gpio -g mode 26 out
gpio -g mode 16 out
main=$(gpio -g read 26)
light=$(gpio -g read 21)
pump=$(gpio -g read 12)
fan=$(gpio -g read 66)
bubl=$(gpio -g read 20)

if [[ $fan -eq 0 ]]
then
	if [[ $main -eq 0 ]]
	then
        	gpio -g write 26 1
	fi
	gpio -g write 16 1
elif [[ $fan -eq 1 ]]
then
	gpio -g write 16 0
fi
sleep 0.5
main=$(gpio -g read 26)
light=$(gpio -g read 21)
pump=$(gpio -g read 12)
fan=$(gpio -g read 16)
echo -e "Main AC relay: " $main
echo -e "Fan AC relay: "$fan

