#! /bin/sh
if [ $# -eq 0 ]
then
	delay='1'
else
	delay=$1
fi
Pump=$(raspi-gpio get 21 | awk -F" " '{print $3}' |awk -F"=" '{print $2}')
Main=$(raspi-gpio get 26 | awk -F" " '{print $3}' |awk -F"=" '{print $2}')
hall=$(./hall)

if [ "$Main" -eq "0"  ]
then
	raspi-gpio set 26 dh
fi
if [ "$Pump" -eq "0" ] && [ "$hall"  -eq "0" ]
then
        raspi-gpio set 21 dh
fi

while true
do
	date=$(date +%T)
	hall=$(./hall)
	while [ $hall -eq 0 ]
	do
		date=$(date +%T)
		echo $date" ,nothing"
		hall=$(./hall)
		sleep $delay
	done
	hall=$(./hall)
	count=0
	while [ $hall -eq 1 ]
	do
		count=$(echo "scale=1;" $count "+ 1" | bc)
		if [ "$count" -gt "5" ]
		then
			raspi-gpio set 21 dl
			date=$(date +%T)
			echo $date" ,Draining"
			hall=$(./hall)
		fi
		sleep $delay
	done
done
