#! /bin/sh
if [ $# -eq 0 ]
then
	delay='1'
else
	delay=$1
fi
while true
do
	date=$(date +%T)
	hall=$(./hall)
	while [ $hall -eq 0 ]
	do
		date=$(date +%T)
		echo $date" ,nothing"
		hall=$(./hall)
		sleep $delay
	done
	hall=$(./hall)
	while [ $hall -eq 1 ]
	do
		date=$(date +%T)
#		raspi-gpio set 21 dl
		echo $date" ,Draining"
		hall=$(./hall)
		sleep $delay
	done
done
