#! /bin/sh
while true
do
	date=$(date +%T)
	hall=$(./hall)
	while [ $hall -eq 0 ]
	do
		date=$(date +%T)
		echo $date" ,nothing"
		hall=$(./hall)
	done
	hall=$(./hall)
	while [ $hall -eq 1 ]
	do
		date=$(date +%T)
		echo $date" ,Draining"
		hall=$(./hall)
	done
done
