#! /bin/bash

gpio -g mode 26 out
gpio -g mode 12 out
main=$(gpio -g read 26)
light=$(gpio -g read 21)
pump=$(gpio -g read 12)
fan=$(gpio -g read 16)
bubl=$(gpio -g read 20)


if [[ $pump -eq 0 ]]
then
	if [[ $main -eq 0 ]]
	then
        	gpio -g write 26 1
	fi
	gpio -g write 12 1
elif [[ $pump -eq 1 ]]
then
	gpio -g write 12 0
	if [[ $light -eq 0 && $fan -eq 0 && $fbubl -eq 0 ]]
	then
		gpio -g write 26 0
	fi
fi
sleep 0.5
main=$(gpio -g read 26)
pump=$(gpio -g read 12)
echo -e "Main AC relay: " $main
echo -e "pump AC relay: "$pump
