#! /usr/bin/env python3
import time 
import busio 
import board 
import adafruit_shtc3
 
i2c = busio.I2C(board.SCL, board.SDA) 
sht = adafruit_shtc3.SHTC3(i2c)
 
temperature, relative_humidity = sht.measurements 
print("Humidity: %0.1f %%" % relative_humidity)
