#!/usr/bin/env python
import time
import serial

ser = serial.Serial(
        port='/dev/ttyAMA0',
        baudrate = 115800,
        parity=serial.PARITY_NONE,
        stopbits=serial.STOPBITS_ONE,
        bytesize=serial.EIGHTBITS,
        timeout=1
)

while 1:
        #x=ser.readline()
	try:
		value = str(ser.readline().strip())
        	value = value.strip("'b'")
        	if value:
			print value
	except serial.serialutil.SerialException:
		pass
	time.sleep(0.1)
