#!/usr/bin/env python
import time
import serial
import sys
itt=0
ser = serial.Serial(
        port='/dev/ttyAMA0', #Replace ttyS0 with ttyAM0 for Pi1,Pi2,Pi0
        baudrate = 115800,
        parity=serial.PARITY_NONE,
        stopbits=serial.STOPBITS_ONE,
        bytesize=serial.EIGHTBITS,
        timeout=1
)
counter=0

if len(sys.argv) == 1:
	print ("Usage : Valve [Param]")
	print ("              [1-3] valve position selection")
	print ("              [t/T] Temperature")
	print ("              [s/S] Status of the valve and Hall sensors")
	print ("              [q/Q] quit, respawn main() on RP2040")
else:
		argnum =  len(sys.argv)
		if argnum > 3:
			value = 0
		else:
			value = str(sys.argv[1])
		ser.write("V%s \n"%(value ))
		while 1:
			try:
				value = str(ser.readline().strip())
				value = value.strip("'b'")
       				if value:
					itt = itt + 1
					print value
#					sys.exit()
			except serial.serialutil.SerialException:
				pass
