#!/usr/bin/env python
#!/usr/bin/env python
import time
import serial
import sys

ser = serial.Serial(
        port='/dev/ttyAMA0', #Replace ttyS0 with ttyAM0 for Pi1,Pi2,Pi0
        baudrate = 300,
        parity=serial.PARITY_NONE,
        stopbits=serial.STOPBITS_ONE,
        bytesize=serial.EIGHTBITS,
        timeout=1
)
counter=0

while 1:
	if len(sys.argv) == 1:
		for counter in range(4):
			print ("V%d \n"%(counter))
			ser.write("V%d \n"%(counter))
        		time.sleep(1)
        		counter += 1
	else:
			argnum =  len(sys.argv)
			if argnum > 3:
				value = 0
			else:
				value = str(sys.argv[1])
			ser.write("V%s \n"%(value ))
			time.sleep(1)
			exit()
